---
- name: Install sdelete
  win_chocolatey:
    name: sdelete
    state: present

- name: Defragment all local volumes (in parallel)
  community.windows.win_defrag:
    parallel: yes

- name: sdelete C drive
  win_shell: 'sdelete -z C:'