---

- name: search for Windows updates 
  win_updates:
    state: searched
  register: update_search_result

- name: show updates to install
  debug:
    msg: "{{ update_search_result }}"

- name: pre reboot, if needed
  win_reboot:
    reboot_timeout: 6000
  when: update_search_result.reboot_required

- name: Install Windows Updates
  win_updates:
  register: update_result

- name: show update_result
  debug:
    msg: "{{ update_result }}"

# - name: reboot, if needed
#   win_reboot:
#     reboot_timeout: 6000
#   when: update_result.reboot_required