- hosts: all

  vars:

    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

    ansible_winrm_connection_timeout: 3600 
    ansible_winrm_operation_timeout_sec: 3600 
    ansible_winrm_read_timeout_sec: 3600

    ansible_become_method: runas
    ansible_become_flags: logon_type=batch
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"

    vdagent_win_version: 0.10.0

  tasks:

  - name: wait for system to become reachable
    wait_for_connection:

  - name: Disable Hibernate Mode
    win_command: powercfg -h off

  - include: disableWindowsDefender.yml

  - include: installVBTools.yml
    when: ansible_virtualization_type == "VirtualBox"

  - include: qemuTools.yml
    when: ansible_system_vendor == "QEMU"

  - include: installVMwareTools.yml
    when: ansible_virtualization_type == "VMware"

  # - include: installUpdates.yml

  - include: windows10Customization.yml
    when: ansible_os_name == "Microsoft Windows 10 Pro"

  - include: appxPackages.yml
    when: ansible_os_name == "Microsoft Windows 10 Pro"

  # - include: cleanUp.yml