# - hosts: 127.0.0.1
#   connection: local

#   tasks:
#   - ping:

- hosts: all

  vars:

    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore

    ansible_winrm_connection_timeout: 3600 
    ansible_winrm_operation_timeout_sec: 3600 
    ansible_winrm_read_timeout_sec: 3600

    ansible_become_method: runas
    ansible_become_flags: logon_type=batch
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_password: "{{ ansible_password }}"

    vdagent_win_version: 0.10.0

  tasks:

  - name: wait for system to become reachable
    wait_for_connection:

  - name: Disable Hibernate Mode
    win_command: powercfg -h off

  - include_tasks: disableWindowsDefender.yml

  - include_tasks: installVBTools.yml
    when: ansible_virtualization_type == "VirtualBox"

  - include_tasks: qemuTools.yml
    when: ansible_system_vendor == "QEMU"

  - include_tasks: installVMwareTools.yml
    when: ansible_virtualization_type == "VMware"

  - include_tasks: installUpdates.yml

  - include_tasks: appxPackages.yml
    when: ansible_os_name == "Microsoft Windows 10 Pro" or 
          ansible_os_name == "Microsoft Windows 11 Pro" or 
          ansible_os_name == "Microsoft Windows 10 Enterprise Evaluation" or 
          ansible_os_name == "Microsoft Windows 11 Enterprise Evaluation"

  - include_tasks: windows10.yml
    when: ansible_os_name == "Microsoft Windows 10 Pro" or 
          ansible_os_name == "Microsoft Windows 10 Enterprise Evaluation"

  - include_tasks: windows11.yml
    when: ansible_os_name == "Microsoft Windows 11 Pro" or
          ansible_os_name == "Microsoft Windows 11 Enterprise Evaluation"

  - include_tasks: chocolatey.yml

  - include_tasks: cleanUp.yml