---
- name: LayoutModification Taskbar xml
  ansible.windows.win_copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <LayoutModificationTemplate
          xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification"
          xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout"
          xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout"
          xmlns:taskbar="http://schemas.microsoft.com/Start/2014/TaskbarLayout"
          Version="1">
        <CustomTaskbarLayoutCollection>
          <defaultlayout:TaskbarLayout>
            <taskbar:TaskbarPinList>
              <taskbar:DesktopApp DesktopApplicationID="Microsoft.Windows.Explorer" />
              <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk" />
            </taskbar:TaskbarPinList>
          </defaultlayout:TaskbarLayout>
      </CustomTaskbarLayoutCollection>
      </LayoutModificationTemplate>
    dest: C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml
  when: ansible_os_name == "Microsoft Windows 11 Pro"

- name: LayoutModification Start json
  ansible.windows.win_copy:
    content: |
      {
        "pinnedList":[
          {"desktopAppLink":"%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\This PC.lnk"},
          {"desktopAppLink":"%ALLUSERSPROFILE%\\Microsoft\\Windows\\Start Menu\\Programs\\Administrative Tools\\Computer Management.lnk"},
          {"packagedAppId":"windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"},
          {"desktopAppLink":"%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Windows PowerShell\\Windows PowerShell.lnk"},
          {"packagedAppId":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},
          {"desktopAppLink":"%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\File Explorer.lnk"}
        ]
      }
    dest: C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.json
  when: ansible_os_name == "Microsoft Windows 11 Pro"


# - name: "createreg path"
#   win_regedit:
#     path: "{{ item.path }}"
#     state: present
#   loop:
#     - { path: 'HKLM:\Software\Policies\Microsoft\Windows\Windows Chat' }
#     - { path: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Communications' 


# - name: Remove MicrosoftTeams
#   win_shell: | 
#     Get-AppxPackage MicrosoftTeams*|Remove-AppxPackage -AllUsers
#     Get-AppxProvisionedPackage -online | where-object {$_.PackageName -like "*MicrosoftTeams*"} | Remove-AppxProvisionedPackage -online -Verbose
#     reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Communications /v ConfigureChatAutoInstall /t REG_DWORD /d 0 /f

- name: "desktop"
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
    state: present
  loop:
    - { path: 'HKLM:\Software\Policies\Microsoft\Windows\Windows Chat', name: 'ChatIcon', data: '3' } # disable Chat