---
- name: LayoutModification
  ansible.windows.win_copy:
    content: |
      <LayoutModificationTemplate 
      xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout" 
      xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout" 
      xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification"
      xmlns:taskbar="http://schemas.microsoft.com/Start/2014/TaskbarLayout"
      Version="1">
        <LayoutOptions StartTileGroupCellWidth="6" />
        
        <DefaultLayoutOverride>
          <StartLayoutCollection>
            <defaultlayout:StartLayout GroupCellWidth="6">
            </defaultlayout:StartLayout>
          </StartLayoutCollection>
        </DefaultLayoutOverride>

        <CustomTaskbarLayoutCollection PinListPlacement="Replace">
          <defaultlayout:TaskbarLayout>
            <taskbar:TaskbarPinList>
              <taskbar:DesktopApp DesktopApplicationLinkPath="%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk" />
            </taskbar:TaskbarPinList>
          </defaultlayout:TaskbarLayout>
        </CustomTaskbarLayoutCollection>

      </LayoutModificationTemplate>
    dest: C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml

- name: "Change ContentDeliveryManager settings for new users"
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'ContentDeliveryAllowed', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'OemPreInstalledAppsEnabled', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'PreInstalledAppsEnabled', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'PreInstalledAppsEverEnabled', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'SilentInstalledAppsEnabled', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'SoftLandingEnabled', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'SubscribedContentEnabled', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', name: 'SystemPaneSuggestionsEnabled', data: '0' }

- name: Remove registry path SuggestedApps for new users
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SuggestedApps
    state: absent
    delete_key: yes
    hive: C:\Users\Default\NTUSER.dat

- name: Remove registry path Subscriptions for new users
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\Subscriptions
    state: absent
    delete_key: yes
    hive: C:\Users\Default\NTUSER.dat

# disable Cortana
- name: "disable Cortana"
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Search', name: 'CortanaConsent', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Search', name: 'AllowSearchToUseLocation', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Search', name: 'BingSearchEnabled', data: '0' }
    - { path: 'HKLM:\Software\Policies\Microsoft\Windows\Windows Search', name: 'AllowCortana', data: '0' }
    - { path: 'HKLM:\Software\Policies\Microsoft\Windows\Windows Search', name: 'DisableWebSearch', data: '1' }

# Desktop 
- name: "Desktop"  
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'HideSCAMeetNow', data: '1' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', name: 'AllowOnlineTips', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Search', name: 'SearchboxTaskbarMode', data: '1' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', name: 'ShowCortanaButton', data: '0' }
    - { path: 'HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel', name: '{20D04FE0-3AEA-1069-A2D8-08002B30309D}', data: '0' }
    - { path: 'HKLM:\Software\Policies\Microsoft\EdgeUpdate', name: 'CreateDesktopShortcutDefault', data: '0' }
    - { path: 'HKLM:\Software\Policies\Microsoft\EdgeUpdate', name: 'InstallDefault', data: '0' }

- name: "Disable taskbar weather and news"
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
    - { path: 'HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds', name: 'ShellFeedsTaskbarOpenOnHover', data: '0' }
    - { path: 'HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds', name: 'ShellFeedsTaskbarViewMode', data: '2' }
    - { path: 'HKLM:\ANSIBLE\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds', name: 'ShellFeedsTaskbarContentUpdateMode', data: '1' }

- name: Remove registry path OneDriveSetup for new users
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Run
    name: OneDriveSetup
    state: absent
    delete_key: yes
    hive: C:\Users\Default\NTUSER.dat